version: '2'
services:
    userextra-app:
        image: userextra
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://userextra-postgresql:5432/userExtra
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    userextra-postgresql:
        extends:
            file: postgresql.yml
            service: userextra-postgresql
